CREATE TABLE washing_machines (
    id INTEGER PRIMARY KEY,
    name TEXT,
    brand TEXT,
    type TEXT,
    size TEXT,
    price INTEGER,
    color TEXT,
    warranty TEXT,
    energy_rating TEXT,
    features TEXT
);

CREATE TABLE fridges (
    id INTEGER PRIMARY KEY,
    name TEXT,
    brand TEXT,
    type TEXT,
    size TEXT,
    price INTEGER,
    color TEXT,
    warranty TEXT,
    energy_rating TEXT,
    features TEXT
);

CREATE TABLE tvs (
    id INTEGER PRIMARY KEY,
    name TEXT,
    brand TEXT,
    type TEXT,
    size TEXT,
    price INTEGER,
    color TEXT,
    warranty TEXT,
    resolution TEXT,
    features TEXT
);

CREATE TABLE dishwashers (
    id INTEGER PRIMARY KEY,
    name TEXT,
    brand TEXT,
    type TEXT,
    size TEXT,
    price INTEGER,
    color TEXT,
    warranty TEXT,
    energy_rating TEXT,
    features TEXT
);

INSERT INTO washing_machines (id, name, brand, type, size, price, color, warranty, energy_rating, features) VALUES 
(1, 'WM-Front-7', 'LG', 'Front Load', '7kg', 349, 'White', '2 years', 'A+++', 'Inverter, Steam, 1400rpm'),
(2, 'WM-Top-6', 'Samsung', 'Top Load', '6kg', 289, 'Silver', '1 year', 'A++', 'Digital Display, Quick Wash'),
(3, 'WM-Front-9', 'Bosch', 'Front Load', '9kg', 549, 'White', '2 years', 'A+++', 'EcoSilence, ActiveWater'),
(4, 'WM-Front-8', 'Siemens', 'Front Load', '8kg', 499, 'Silver', '2 years', 'A+++', 'iQdrive, varioPerfect'),
(5, 'WM-Top-7', 'Whirlpool', 'Top Load', '7kg', 329, 'Grey', '1 year', 'A++', '6th Sense, Hard Water Wash'),
(6, 'WM-Front-10', 'LG', 'Front Load', '10kg', 649, 'Black', '3 years', 'A+++', 'AI DD, TurboWash, Steam'),
(7, 'WM-Front-8', 'Samsung', 'Front Load', '8kg', 449, 'White', '2 years', 'A+++', 'AddWash, EcoBubble'),
(8, 'WM-Top-6.5', 'Haier', 'Top Load', '6.5kg', 269, 'Grey', '1 year', 'A+', 'Fuzzy Logic, Dual Spray'),
(9, 'WM-Front-7', 'Beko', 'Front Load', '7kg', 299, 'White', '2 years', 'A++', 'AquaWave, ProSmart Inverter'),
(10, 'WM-Front-9', 'Miele', 'Front Load', '9kg', 899, 'White', '5 years', 'A+++', 'TwinDos, CapDosing'),
(11, 'WM-Top-8', 'LG', 'Top Load', '8kg', 379, 'Silver', '2 years', 'A+++', 'Smart Inverter, Jet Spray'),
(12, 'WM-Front-7', 'Panasonic', 'Front Load', '7kg', 399, 'White', '2 years', 'A+++', 'Ag+ Antibacterial, Econavi'),
(13, 'WM-Front-8', 'Whirlpool', 'Front Load', '8kg', 429, 'Silver', '2 years', 'A+++', 'Fresh Care+, Steam Hygiene'),
(14, 'WM-Top-7', 'Samsung', 'Top Load', '7kg', 319, 'White', '1 year', 'A++', 'Wobble Technology, Magic Filter'),
(15, 'WM-Front-6', 'Bosch', 'Front Load', '6kg', 379, 'White', '2 years', 'A+++', 'VarioDrum, Reload Function'),
(16, 'WM-Front-10', 'Samsung', 'Front Load', '10kg', 699, 'Black', '3 years', 'A+++', 'QuickDrive, AddWash, AI Control'),
(17, 'WM-Front-8', 'LG', 'Front Load', '8kg', 479, 'Silver', '2 years', 'A+++', 'Steam+, AI DD, NFC'),
(18, 'WM-Top-9', 'Haier', 'Top Load', '9kg', 399, 'Grey', '2 years', 'A+++', 'Power Wave, Near Zero Water'),
(19, 'WM-Front-7', 'Electrolux', 'Front Load', '7kg', 449, 'White', '2 years', 'A+++', 'UltraMix, SensiCare'),
(20, 'WM-Front-8', 'Siemens', 'Front Load', '8kg', 529, 'Silver', '2 years', 'A+++', 'homeConnect, iQ500'),
(21, 'WM-Top-6', 'Beko', 'Top Load', '6kg', 249, 'White', '1 year', 'A+', '3D Aquawave, Child Lock'),
(22, 'WM-Front-9', 'LG', 'Front Load', '9kg', 579, 'Black', '2 years', 'A+++', 'TrueSteam, Smart Diagnosis'),
(23, 'WM-Front-7', 'Candy', 'Front Load', '7kg', 279, 'White', '1 year', 'A++', 'Rapid Wash, NFC Connect'),
(24, 'WM-Top-8', 'Whirlpool', 'Top Load', '8kg', 369, 'Grey', '2 years', 'A++', 'Impeller Wash, Soak Mode'),
(25, 'WM-Front-8', 'Bosch', 'Front Load', '8kg', 499, 'White', '2 years', 'A+++', 'Home Connect, EcoSilence Drive'),
(26, 'WM-Front-6', 'Samsung', 'Front Load', '6kg', 349, 'White', '1 year', 'A+++', 'Digital Inverter, Diamond Drum'),
(27, 'WM-Top-7.5', 'LG', 'Top Load', '7.5kg', 359, 'Silver', '2 years', 'A+++', 'Smart Inverter, 6 Motion'),
(28, 'WM-Front-10', 'Miele', 'Front Load', '10kg', 999, 'White', '5 years', 'A+++', 'Miele@home, SingleWash'),
(29, 'WM-Front-7', 'Haier', 'Front Load', '7kg', 369, 'Grey', '2 years', 'A+++', 'Direct Motion Motor, ABT'),
(30, 'WM-Front-8', 'Panasonic', 'Front Load', '8kg', 469, 'Silver', '2 years', 'A+++', 'nanoe X, Auto Dose'),
(31, 'WM-Top-6', 'Beko', 'Top Load', '6kg', 239, 'White', '1 year', 'A+', 'GentleCare, Fast Wash'),
(32, 'WM-Front-9', 'Siemens', 'Front Load', '9kg', 629, 'Silver', '3 years', 'A+++', 'iQ700, sensoFresh'),
(33, 'WM-Front-7', 'Electrolux', 'Front Load', '7kg', 419, 'White', '2 years', 'A+++', 'PerfectCare 600, AutoDose'),
(34, 'WM-Top-8', 'Samsung', 'Top Load', '8kg', 389, 'Grey', '2 years', 'A+++', 'EcoBubble, Wobble Technology'),
(35, 'WM-Front-8', 'LG', 'Front Load', '8kg', 499, 'White', '2 years', 'A+++', 'AI DD, Steam, ThinQ'),
(36, 'WM-Front-6', 'Whirlpool', 'Front Load', '6kg', 329, 'Silver', '1 year', 'A++', '6th Sense Live, ZEN Technology'),
(37, 'WM-Top-7', 'Haier', 'Top Load', '7kg', 299, 'White', '1 year', 'A++', 'Smart Dual Wash, Magic Filter'),
(38, 'WM-Front-10', 'Bosch', 'Front Load', '10kg', 749, 'White', '3 years', 'A+++', 'Series 8, Home Connect'),
(39, 'WM-Front-7', 'Beko', 'Front Load', '7kg', 319, 'Grey', '2 years', 'A+++', 'SteamCure, Pet Hair Removal'),
(40, 'WM-Front-8', 'Candy', 'Front Load', '8kg', 299, 'White', '1 year', 'A+++', 'Rapid Wash 59, Smart Touch'),
(41, 'WM-Top-9', 'LG', 'Top Load', '9kg', 429, 'Silver', '2 years', 'A+++', 'TurboDrum, Smart Inverter'),
(42, 'WM-Front-7', 'Miele', 'Front Load', '7kg', 799, 'White', '5 years', 'A+++', 'Honeycomb Drum, WaterPlus'),
(43, 'WM-Front-8', 'Samsung', 'Front Load', '8kg', 519, 'Black', '2 years', 'A+++', 'Hygiene Steam, Super Speed'),
(44, 'WM-Top-6.5', 'Whirlpool', 'Top Load', '6.5kg', 279, 'White', '1 year', 'A++', 'Spiro Wash, Hard Water Softener'),
(45, 'WM-Front-9', 'Panasonic', 'Front Load', '9kg', 549, 'Silver', '2 years', 'A+++', 'G-Tech Motor, Ag+ Antibacterial'),
(46, 'WM-Front-7', 'Siemens', 'Front Load', '7kg', 449, 'White', '2 years', 'A+++', 'iQ300, speedPerfect'),
(47, 'WM-Top-8', 'Beko', 'Top Load', '8kg', 339, 'Grey', '2 years', 'A++', 'Steam Iron, Fast+'),
(48, 'WM-Front-8', 'Electrolux', 'Front Load', '8kg', 489, 'White', '2 years', 'A+++', 'PerfectCare 800, Steam System'),
(49, 'WM-Front-6', 'Haier', 'Front Load', '6kg', 319, 'White', '1 year', 'A++', 'PuriSteam, Near Zero Water'),
(50, 'WM-Top-7', 'Samsung', 'Top Load', '7kg', 329, 'Silver', '2 years', 'A+++', 'Digital Inverter, Soft Closing Lid'),
(51, 'WM-Front-10', 'LG', 'Front Load', '10kg', 679, 'Black', '3 years', 'A+++', 'AI DD, TurboWash 360, Steam'),
(52, 'WM-Front-7', 'Bosch', 'Front Load', '7kg', 429, 'Silver', '2 years', 'A+++', 'VarioPerfect, Reload Function'),
(53, 'WM-Top-8', 'Haier', 'Top Load', '8kg', 359, 'Grey', '2 years', 'A+++', 'Power Wave 2.0, Dual Spray'),
(54, 'WM-Front-8', 'Whirlpool', 'Front Load', '8kg', 459, 'White', '2 years', 'A+++', 'Steam Refresh, 6th Sense'),
(55, 'WM-Front-9', 'LG', 'Front Load', '9kg', 599, 'Silver', '2 years', 'A+++', 'TrueSteam+, AI DD, NFC Tag'),
(56, 'WM-Top-6', 'Candy', 'Top Load', '6kg', 229, 'White', '1 year', 'A+', 'Quick Wash 40, Digital Display'),
(57, 'WM-Front-7', 'Miele', 'Front Load', '7kg', 849, 'White', '5 years', 'A+++', 'CapDosing, AutoClean Dispenser'),
(58, 'WM-Front-8', 'Samsung', 'Front Load', '8kg', 549, 'White', '2 years', 'A+++', 'EcoBubble, AddWash, AI Wash'),
(59, 'WM-Top-7.5', 'Beko', 'Top Load', '7.5kg', 309, 'Silver', '2 years', 'A++', 'Steam Wash, Anti-Allergy'),
(60, 'WM-Front-10', 'Siemens', 'Front Load', '10kg', 799, 'Silver', '3 years', 'A+++', 'iQ700, AutoDose, Home Connect'),
(61, 'WM-Front-6', 'Panasonic', 'Front Load', '6kg', 349, 'White', '2 years', 'A+++', 'Econavi, Ag+ Technology'),
(62, 'WM-Top-8', 'LG', 'Top Load', '8kg', 399, 'Grey', '2 years', 'A+++', 'Smart Inverter, Jet Spray+'),
(63, 'WM-Front-7', 'Electrolux', 'Front Load', '7kg', 439, 'White', '2 years', 'A+++', 'SensiCare System, Time Manager'),
(64, 'WM-Front-8', 'Haier', 'Front Load', '8kg', 419, 'Silver', '2 years', 'A+++', 'Direct Motion, PuriSteam'),
(65, 'WM-Top-9', 'Samsung', 'Top Load', '9kg', 449, 'White', '2 years', 'A+++', 'EcoBubble, Wobble Tech, AI Control'),
(66, 'WM-Front-7', 'Whirlpool', 'Front Load', '7kg', 379, 'Grey', '2 years', 'A+++', 'Fresh Care, Steam Hygiene+'),
(67, 'WM-Front-9', 'Bosch', 'Front Load', '9kg', 599, 'White', '3 years', 'A+++', 'Series 6, EcoSilence, Home Connect'),
(68, 'WM-Top-6.5', 'Beko', 'Top Load', '6.5kg', 259, 'White', '1 year', 'A++', '3D Aquawave, Child Lock'),
(69, 'WM-Front-8', 'Candy', 'Front Load', '8kg', 289, 'Silver', '1 year', 'A+++', 'Rapid Wash, Smart AI'),
(70, 'WM-Front-10', 'Miele', 'Front Load', '10kg', 1099, 'White', '5 years', 'A+++', 'TwinDos, QuickPowerWash'),
(71, 'WM-Front-7', 'LG', 'Front Load', '7kg', 389, 'White', '2 years', 'A+++', 'AI DD, Steam, Smart Pairing'),
(72, 'WM-Top-8', 'Haier', 'Top Load', '8kg', 369, 'Grey', '2 years', 'A+++', 'Smart Dual Wash, Power Wave'),
(73, 'WM-Front-8', 'Samsung', 'Front Load', '8kg', 499, 'Silver', '2 years', 'A+++', 'QuickDrive, Hygiene Steam'),
(74, 'WM-Front-6', 'Siemens', 'Front Load', '6kg', 399, 'White', '2 years', 'A+++', 'iQ300, varioDrum'),
(75, 'WM-Top-7', 'Whirlpool', 'Top Load', '7kg', 319, 'White', '1 year', 'A++', '6th Sense, Soak & Wash'),
(76, 'WM-Front-9', 'Panasonic', 'Front Load', '9kg', 569, 'Silver', '2 years', 'A+++', 'nanoe X, G-Tech Motor'),
(77, 'WM-Front-7', 'Electrolux', 'Front Load', '7kg', 409, 'White', '2 years', 'A+++', 'UltraMix, ProSteam'),
(78, 'WM-Top-6', 'Beko', 'Top Load', '6kg', 249, 'Grey', '1 year', 'A+', 'GentleCare, AquaTech'),
(79, 'WM-Front-8', 'LG', 'Front Load', '8kg', 469, 'Black', '2 years', 'A+++', 'Steam+, AI DD, ThinQ WiFi'),
(80, 'WM-Front-10', 'Bosch', 'Front Load', '10kg', 699, 'Silver', '3 years', 'A+++', 'Series 6, ActiveWater Plus'),
(81, 'WM-Top-8', 'Samsung', 'Top Load', '8kg', 379, 'White', '2 years', 'A+++', 'Digital Inverter, Magic Filter'),
(82, 'WM-Front-7', 'Haier', 'Front Load', '7kg', 359, 'White', '2 years', 'A+++', 'ABT, Direct Motion Motor'),
(83, 'WM-Front-9', 'Whirlpool', 'Front Load', '9kg', 529, 'Silver', '2 years', 'A+++', 'Steam Refresh, Auto Dose'),
(84, 'WM-Top-7.5', 'LG', 'Top Load', '7.5kg', 369, 'Silver', '2 years', 'A+++', 'TurboDrum, Smart Inverter+'),
(85, 'WM-Front-8', 'Miele', 'Front Load', '8kg', 899, 'White', '5 years', 'A+++', 'Miele@home, SingleWash'),
(86, 'WM-Front-6', 'Candy', 'Front Load', '6kg', 259, 'White', '1 year', 'A++', 'Rapid Wash 30, NFC'),
(87, 'WM-Top-9', 'Beko', 'Top Load', '9kg', 389, 'Grey', '2 years', 'A+++', 'Steam Cure, Fast+'),
(88, 'WM-Front-7', 'Siemens', 'Front Load', '7kg', 469, 'Silver', '2 years', 'A+++', 'iQ500, speedPerfect+'),
(89, 'WM-Front-8', 'Panasonic', 'Front Load', '8kg', 489, 'White', '2 years', 'A+++', 'Auto Dose, nanoe X'),
(90, 'WM-Top-6.5', 'Haier', 'Top Load', '6.5kg', 279, 'White', '1 year', 'A++', 'Fuzzy Logic, Dual Spray'),
(91, 'WM-Front-10', 'Samsung', 'Front Load', '10kg', 729, 'Black', '3 years', 'A+++', 'AI Control, QuickDrive, Steam'),
(92, 'WM-Front-7', 'Electrolux', 'Front Load', '7kg', 429, 'Silver', '2 years', 'A+++', 'PerfectCare 700, SensiCare'),
(93, 'WM-Top-8', 'Whirlpool', 'Top Load', '8kg', 359, 'Grey', '2 years', 'A++', 'Impeller, Heavy Duty'),
(94, 'WM-Front-8', 'LG', 'Front Load', '8kg', 509, 'White', '2 years', 'A+++', 'AI DD, TurboWash, Steam'),
(95, 'WM-Front-9', 'Bosch', 'Front Load', '9kg', 619, 'Silver', '3 years', 'A+++', 'Home Connect, iQ500'),
(96, 'WM-Top-7', 'Candy', 'Top Load', '7kg', 289, 'White', '1 year', 'A++', 'Smart Touch, Rapid Wash'),
(97, 'WM-Front-6', 'Miele', 'Front Load', '6kg', 749, 'White', '5 years', 'A+++', 'Honeycomb Drum, WaterPlus'),
(98, 'WM-Front-8', 'Haier', 'Front Load', '8kg', 439, 'Grey', '2 years', 'A+++', 'PuriSteam, Near Zero Water'),
(99, 'WM-Top-9', 'Samsung', 'Top Load', '9kg', 469, 'Silver', '2 years', 'A+++', 'EcoBubble, Wobble, AI Wash'),
(100, 'WM-Front-7', 'Beko', 'Front Load', '7kg', 329, 'White', '2 years', 'A+++', 'SteamCure, Pet Hair');

INSERT INTO fridges (id, name, brand, type, size, price, color, warranty, energy_rating, features) VALUES 
(1, 'RF-Double-280', 'LG', 'Double Door', '280L', 449, 'Silver', '2 years', 'A++', 'Frost Free, Smart Inverter'),
(2, 'RF-Single-190', 'Samsung', 'Single Door', '190L', 329, 'White', '1 year', 'A+', 'Direct Cool, Base Stand'),
(3, 'RF-Side-550', 'LG', 'Side-by-Side', '550L', 899, 'Black', '2 years', 'A+++', 'Ice & Water Dispenser, Door Cooling+'),
(4, 'RF-Triple-380', 'Samsung', 'Triple Door', '380L', 649, 'Silver', '2 years', 'A++', 'Convertible, Digital Inverter'),
(5, 'RF-Compact-150', 'Haier', 'Single Door', '150L', 249, 'Red', '1 year', 'A', 'Mini Bar, Reversible Door'),
(6, 'RF-French-500', 'Whirlpool', 'French Door', '500L', 999, 'Stainless Steel', '3 years', 'A+++', '6th Sense, Air Lifter'),
(7, 'RF-Double-320', 'Bosch', 'Double Door', '320L', 549, 'Silver', '2 years', 'A+++', 'VitaFresh, NoFrost'),
(8, 'RF-Single-220', 'LG', 'Single Door', '220L', 379, 'White', '2 years', 'A++', 'Smart Inverter, Base Grill'),
(9, 'RF-Side-600', 'Samsung', 'Side-by-Side', '600L', 1099, 'Black', '3 years', 'A+++', 'Family Hub, Twin Cooling'),
(10, 'RF-Triple-420', 'Haier', 'Triple Door', '420L', 699, 'Grey', '2 years', 'A+++', 'Perpendicular Cooling, ABT'),
(11, 'RF-Double-260', 'Whirlpool', 'Double Door', '260L', 429, 'Silver', '2 years', 'A++', 'IntelliSense, Zeolite'),
(12, 'RF-Single-180', 'Beko', 'Single Door', '180L', 299, 'White', '1 year', 'A+', 'EverFresh+, Blue Light'),
(13, 'RF-French-550', 'LG', 'French Door', '550L', 1199, 'Stainless Steel', '3 years', 'A+++', 'Door-in-Door, Crafted Ice'),
(14, 'RF-Double-300', 'Panasonic', 'Double Door', '300L', 499, 'Silver', '2 years', 'A+++', 'Inverter, Ag Clean'),
(15, 'RF-Side-520', 'Bosch', 'Side-by-Side', '520L', 949, 'Black', '2 years', 'A+++', 'VitaFresh Pro, Home Connect'),
(16, 'RF-Triple-360', 'Samsung', 'Triple Door', '360L', 599, 'White', '2 years', 'A++', 'Flex Zone, Metal Cooling'),
(17, 'RF-Compact-120', 'Haier', 'Single Door', '120L', 219, 'Blue', '1 year', 'A', 'Table Top, Reversible'),
(18, 'RF-Double-340', 'Whirlpool', 'Double Door', '340L', 579, 'Grey', '2 years', 'A+++', 'Adaptive Defrost, LED Tower'),
(19, 'RF-Single-200', 'LG', 'Single Door', '200L', 349, 'Silver', '1 year', 'A++', 'Smart Connect, Anti-Bacterial'),
(20, 'RF-French-620', 'Samsung', 'French Door', '620L', 1399, 'Stainless Steel', '3 years', 'A+++', 'FlexZone, Family Hub 2.0'),
(21, 'RF-Double-290', 'Beko', 'Double Door', '290L', 469, 'White', '2 years', 'A++', 'HarvestFresh, NeoFrost'),
(22, 'RF-Side-580', 'Haier', 'Side-by-Side', '580L', 979, 'Black', '2 years', 'A+++', 'My Zone, ABT+'),
(23, 'RF-Triple-400', 'Panasonic', 'Triple Door', '400L', 729, 'Silver', '2 years', 'A+++', 'Prime Fresh+, nanoe X'),
(24, 'RF-Double-270', 'Bosch', 'Double Door', '270L', 489, 'Grey', '2 years', 'A+++', 'VitaFresh, MultiAirflow'),
(25, 'RF-Single-170', 'Whirlpool', 'Single Door', '170L', 289, 'White', '1 year', 'A+', 'Adaptive Defrost, Spill Proof'),
(26, 'RF-French-540', 'LG', 'French Door', '540L', 1099, 'Stainless Steel', '3 years', 'A+++', 'InstaView, Slim Space+'),
(27, 'RF-Double-310', 'Samsung', 'Double Door', '310L', 529, 'Silver', '2 years', 'A+++', 'Digital Inverter, Convertible'),
(28, 'RF-Side-500', 'Beko', 'Side-by-Side', '500L', 849, 'Black', '2 years', 'A+++', 'EverFresh+, ProBlue Glass'),
(29, 'RF-Triple-350', 'Haier', 'Triple Door', '350L', 579, 'Grey', '2 years', 'A++', 'DEO Fresh, TDE Fresh'),
(30, 'RF-Compact-140', 'LG', 'Single Door', '140L', 239, 'Red', '1 year', 'A', 'Smart Inverter, Base Stand'),
(31, 'RF-Double-330', 'Panasonic', 'Double Door', '330L', 559, 'White', '2 years', 'A+++', 'Twin Inverter, Ag Clean'),
(32, 'RF-French-600', 'Bosch', 'French Door', '600L', 1299, 'Stainless Steel', '3 years', 'A+++', 'VitaFresh Pro, Home Connect'),
(33, 'RF-Single-210', 'Samsung', 'Single Door', '210L', 369, 'Silver', '2 years', 'A++', 'Digital Inverter, Cool Pack'),
(34, 'RF-Side-560', 'Whirlpool', 'Side-by-Side', '560L', 929, 'Black', '2 years', 'A+++', '6th Sense, In-Door-Ice'),
(35, 'RF-Triple-390', 'LG', 'Triple Door', '390L', 679, 'Silver', '2 years', 'A+++', 'Door Cooling+, Smart Diagnosis'),
(36, 'RF-Double-250', 'Haier', 'Double Door', '250L', 399, 'White', '2 years', 'A++', 'Jumbo Ice Maker, PuriFresh'),
(37, 'RF-French-580', 'Samsung', 'French Door', '580L', 1249, 'Stainless Steel', '3 years', 'A+++', 'FlexZone Drawer, Twin Cooling+'),
(38, 'RF-Single-160', 'Beko', 'Single Door', '160L', 269, 'Grey', '1 year', 'A+', 'EverFresh, Adjustable Shelves'),
(39, 'RF-Double-300', 'Whirlpool', 'Double Door', '300L', 499, 'Silver', '2 years', 'A+++', 'IntelliSense, Zeolite+'),
(40, 'RF-Side-540', 'Panasonic', 'Side-by-Side', '540L', 999, 'Black', '2 years', 'A+++', 'nanoe X, Inverter Compressor'),
(41, 'RF-Triple-370', 'Bosch', 'Triple Door', '370L', 629, 'Silver', '2 years', 'A+++', 'VitaFresh, NoFrost Plus'),
(42, 'RF-Compact-130', 'Haier', 'Single Door', '130L', 229, 'Blue', '1 year', 'A', 'Reversible Door, Energy Efficient'),
(43, 'RF-Double-280', 'LG', 'Double Door', '280L', 469, 'Grey', '2 years', 'A+++', 'Smart Inverter, Door Alarm'),
(44, 'RF-French-560', 'Whirlpool', 'French Door', '560L', 1149, 'Stainless Steel', '3 years', 'A+++', 'Air Lifter, Active 0C'),
(45, 'RF-Single-190', 'Samsung', 'Single Door', '190L', 339, 'White', '1 year', 'A+', 'Digital Inverter, Cool Wall'),
(46, 'RF-Side-590', 'Haier', 'Side-by-Side', '590L', 1029, 'Black', '2 years', 'A+++', 'My Zone, ABT Pro'),
(47, 'RF-Triple-410', 'Panasonic', 'Triple Door', '410L', 749, 'Silver', '2 years', 'A+++', 'Prime Fresh, nanoe X'),
(48, 'RF-Double-320', 'Beko', 'Double Door', '320L', 519, 'White', '2 years', 'A+++', 'HarvestFresh, NeoFrost Dual'),
(49, 'RF-French-640', 'LG', 'French Door', '640L', 1449, 'Stainless Steel', '3 years', 'A+++', 'InstaView, Crafted Ice Maker'),
(50, 'RF-Single-180', 'Whirlpool', 'Single Door', '180L', 299, 'Grey', '1 year', 'A+', 'Adaptive Defrost, Anti-Bacterial'),
(51, 'RF-Double-290', 'Bosch', 'Double Door', '290L', 509, 'Silver', '2 years', 'A+++', 'VitaFresh, MultiBox'),
(52, 'RF-Side-530', 'Samsung', 'Side-by-Side', '530L', 969, 'Black', '2 years', 'A+++', 'Twin Cooling+, Ice Master'),
(53, 'RF-Triple-380', 'Haier', 'Triple Door', '380L', 649, 'Grey', '2 years', 'A+++', 'Perpendicular Cooling, TDE Fresh'),
(54, 'RF-Compact-150', 'Beko', 'Single Door', '150L', 249, 'Red', '1 year', 'A', 'EverFresh+, Reversible Door'),
(55, 'RF-Double-340', 'LG', 'Double Door', '340L', 589, 'Silver', '2 years', 'A+++', 'Smart Inverter, UVnano'),
(56, 'RF-French-590', 'Panasonic', 'French Door', '590L', 1199, 'Stainless Steel', '3 years', 'A+++', 'nanoe X, Inverter Compressor'),
(57, 'RF-Single-200', 'Whirlpool', 'Single Door', '200L', 349, 'White', '1 year', 'A++', 'IntelliSense, Curd Maestro'),
(58, 'RF-Side-570', 'Bosch', 'Side-by-Side', '570L', 1049, 'Black', '2 years', 'A+++', 'VitaFresh Pro, Home Connect'),
(59, 'RF-Triple-360', 'Samsung', 'Triple Door', '360L', 619, 'Silver', '2 years', 'A+++', 'Flex Zone, Metal Cooling Plate'),
(60, 'RF-Double-270', 'Haier', 'Double Door', '270L', 429, 'White', '2 years', 'A++', 'Jumbo Ice Maker, PuriFresh+'),
(61, 'RF-French-610', 'LG', 'French Door', '610L', 1349, 'Stainless Steel', '3 years', 'A+++', 'Door-in-Door, Ice & Water'),
(62, 'RF-Single-170', 'Beko', 'Single Door', '170L', 279, 'Grey', '1 year', 'A+', 'Blue Light, Adjustable Shelves'),
(63, 'RF-Double-310', 'Panasonic', 'Double Door', '310L', 539, 'Silver', '2 years', 'A+++', 'Twin Inverter, Ag Clean+'),
(64, 'RF-Side-550', 'Whirlpool', 'Side-by-Side', '550L', 949, 'Black', '2 years', 'A+++', '6th Sense, In-Door-Ice Plus'),
(65, 'RF-Triple-400', 'Bosch', 'Triple Door', '400L', 699, 'Silver', '2 years', 'A+++', 'VitaFresh, NoFrost Plus'),
(66, 'RF-Compact-140', 'Samsung', 'Single Door', '140L', 259, 'Blue', '1 year', 'A', 'Digital Inverter, Reversible'),
(67, 'RF-Double-300', 'Haier', 'Double Door', '300L', 489, 'White', '2 years', 'A+++', 'My Zone, ABT'),
(68, 'RF-French-570', 'Beko', 'French Door', '570L', 1099, 'Stainless Steel', '3 years', 'A+++', 'EverFresh+, HarvestFresh Pro'),
(69, 'RF-Single-210', 'LG', 'Single Door', '210L', 369, 'Silver', '2 years', 'A++', 'Smart Inverter, Door Alarm'),
(70, 'RF-Side-600', 'Panasonic', 'Side-by-Side', '600L', 1099, 'Black', '2 years', 'A+++', 'nanoe X, Prime Chill'),
(71, 'RF-Triple-390', 'Whirlpool', 'Triple Door', '390L', 669, 'Grey', '2 years', 'A+++', 'Adaptive Defrost, Zeolite+'),
(72, 'RF-Double-260', 'Samsung', 'Double Door', '260L', 449, 'White', '2 years', 'A+++', 'Digital Inverter, Convertible'),
(73, 'RF-French-630', 'Haier', 'French Door', '630L', 1399, 'Stainless Steel', '3 years', 'A+++', 'My Zone, ABT Pro+'),
(74, 'RF-Single-190', 'Bosch', 'Single Door', '190L', 329, 'Silver', '1 year', 'A++', 'VitaFresh, Low Frost'),
(75, 'RF-Double-330', 'LG', 'Double Door', '330L', 569, 'Grey', '2 years', 'A+++', 'Smart Inverter, Door Cooling+'),
(76, 'RF-Side-520', 'Beko', 'Side-by-Side', '520L', 879, 'Black', '2 years', 'A+++', 'NeoFrost Dual, EverFresh+'),
(77, 'RF-Triple-370', 'Panasonic', 'Triple Door', '370L', 639, 'Silver', '2 years', 'A+++', 'Prime Fresh+, Ag Clean'),
(78, 'RF-Compact-160', 'Whirlpool', 'Single Door', '160L', 279, 'Red', '1 year', 'A+', 'Adaptive Defrost, Spill Proof'),
(79, 'RF-Double-280', 'Haier', 'Double Door', '280L', 459, 'White', '2 years', 'A+++', 'PuriFresh, TDE Fresh'),
(80, 'RF-French-600', 'Samsung', 'French Door', '600L', 1299, 'Stainless Steel', '3 years', 'A+++', 'FlexZone, Family Hub'),
(81, 'RF-Single-180', 'LG', 'Single Door', '180L', 319, 'Grey', '1 year', 'A++', 'Smart Connect, Anti-Bacterial Gasket'),
(82, 'RF-Double-350', 'Bosch', 'Double Door', '350L', 599, 'Silver', '2 years', 'A+++', 'VitaFresh Pro, MultiAirflow'),
(83, 'RF-Side-580', 'Panasonic', 'Side-by-Side', '580L', 1029, 'Black', '2 years', 'A+++', 'Inverter, nanoe X'),
(84, 'RF-Triple-420', 'Whirlpool', 'Triple Door', '420L', 719, 'Silver', '2 years', 'A+++', '6th Sense, IntelliSense'),
(85, 'RF-Compact-130', 'Beko', 'Single Door', '130L', 239, 'Blue', '1 year', 'A', 'EverFresh, Reversible Door'),
(86, 'RF-Double-310', 'Haier', 'Double Door', '310L', 509, 'White', '2 years', 'A+++', 'My Zone, ABT+'),
(87, 'RF-French-580', 'LG', 'French Door', '580L', 1179, 'Stainless Steel', '3 years', 'A+++', 'InstaView, Slim Space+'),
(88, 'RF-Single-200', 'Samsung', 'Single Door', '200L', 359, 'Silver', '2 years', 'A++', 'Digital Inverter, Cool Pack+'),
(89, 'RF-Side-540', 'Bosch', 'Side-by-Side', '540L', 989, 'Black', '2 years', 'A+++', 'VitaFresh, Home Connect'),
(90, 'RF-Triple-380', 'Beko', 'Triple Door', '380L', 659, 'Grey', '2 years', 'A+++', 'HarvestFresh, NeoFrost'),
(91, 'RF-Double-290', 'Panasonic', 'Double Door', '290L', 479, 'White', '2 years', 'A+++', 'Twin Inverter, Ag Clean'),
(92, 'RF-French-620', 'Whirlpool', 'French Door', '620L', 1379, 'Stainless Steel', '3 years', 'A+++', 'Air Lifter, Active 0C Technology'),
(93, 'RF-Single-170', 'Haier', 'Single Door', '170L', 289, 'Grey', '1 year', 'A+', 'PuriFresh, Reversible'),
(94, 'RF-Double-320', 'LG', 'Double Door', '320L', 549, 'Silver', '2 years', 'A+++', 'Smart Inverter, UVnano+'),
(95, 'RF-Side-560', 'Samsung', 'Side-by-Side', '560L', 999, 'Black', '2 years', 'A+++', 'Twin Cooling+, Ice Master Pro'),
(96, 'RF-Triple-400', 'Panasonic', 'Triple Door', '400L', 709, 'Silver', '2 years', 'A+++', 'Prime Fresh, nanoe X'),
(97, 'RF-Compact-150', 'Whirlpool', 'Single Door', '150L', 259, 'Red', '1 year', 'A', 'Adaptive Defrost, Base Grill'),
(98, 'RF-Double-340', 'Haier', 'Double Door', '340L', 579, 'White', '2 years', 'A+++', 'My Zone, ABT Pro'),
(99, 'RF-French-650', 'Bosch', 'French Door', '650L', 1499, 'Stainless Steel', '3 years', 'A+++', 'VitaFresh Pro, Home Connect'),
(100, 'RF-Single-190', 'Beko', 'Single Door', '190L', 329, 'Grey', '1 year', 'A++', 'EverFresh+, Blue Light');

INSERT INTO tvs (id, name, brand, type, size, price, color, warranty, resolution, features) VALUES 
(1, 'TV-LED-32', 'Samsung', 'LED', '32"', 229, 'Black', '1 year', 'HD', 'Tizen OS, HDR10'),
(2, 'TV-QLED-55', 'LG', 'QLED', '55"', 699, 'Silver', '2 years', '4K', 'webOS, AI Picture Pro'),
(3, 'TV-OLED-65', 'Sony', 'OLED', '65"', 1499, 'Black', '3 years', '4K', 'Google TV, XR Processor'),
(4, 'TV-LED-43', 'TCL', 'LED', '43"', 329, 'Black', '1 year', '4K', 'Roku TV, HDR10+'),
(5, 'TV-MiniLED-75', 'Samsung', 'Mini-LED', '75"', 1899, 'Silver', '3 years', '4K', 'Neo QLED, Object Tracking Sound'),
(6, 'TV-LED-50', 'Hisense', 'LED', '50"', 399, 'Black', '2 years', '4K', 'Vidaa, Dolby Vision'),
(7, 'TV-QLED-65', 'TCL', 'QLED', '65"', 799, 'Black', '2 years', '4K', 'Google TV, Mini LED'),
(8, 'TV-OLED-55', 'LG', 'OLED', '55"', 1099, 'Silver', '2 years', '4K', 'webOS 23, Gallery Design'),
(9, 'TV-LED-40', 'Philips', 'LED', '40"', 299, 'Black', '1 year', 'Full HD', 'Android TV, Ambilight'),
(10, 'TV-LED-55', 'Samsung', 'LED', '55"', 549, 'Black', '2 years', '4K', 'Crystal Processor, HDR'),
(11, 'TV-QLED-75', 'Sony', 'QLED', '75"', 1799, 'Silver', '3 years', '4K', 'Google TV, XR Triluminos'),
(12, 'TV-LED-32', 'Haier', 'LED', '32"', 199, 'Black', '1 year', 'HD', 'Android TV, Chromecast'),
(13, 'TV-OLED-77', 'LG', 'OLED', '77"', 2499, 'Black', '3 years', '4K', 'webOS, α9 AI Processor'),
(14, 'TV-LED-43', 'Samsung', 'LED', '43"', 349, 'Silver', '1 year', '4K', 'Tizen, HDR10+'),
(15, 'TV-MiniLED-65', 'TCL', 'Mini-LED', '65"', 999, 'Black', '2 years', '4K', 'Google TV, 120Hz VRR'),
(16, 'TV-LED-50', 'Philips', 'LED', '50"', 449, 'Black', '2 years', '4K', 'Android TV, P5 Processor'),
(17, 'TV-QLED-55', 'Hisense', 'QLED', '55"', 599, 'Silver', '2 years', '4K', 'Vidaa U7, Dolby Atmos'),
(18, 'TV-OLED-65', 'Panasonic', 'OLED', '65"', 1399, 'Black', '3 years', '4K', 'My Home Screen, HCX Pro'),
(19, 'TV-LED-40', 'Sharp', 'LED', '40"', 279, 'Black', '1 year', 'Full HD', 'Android TV, Aquos'),
(20, 'TV-LED-65', 'LG', 'LED', '65"', 649, 'Silver', '2 years', '4K', 'webOS, AI Sound'),
(21, 'TV-QLED-85', 'Samsung', 'QLED', '85"', 2799, 'Silver', '3 years', '4K', 'Neo QLED, Infinity Screen'),
(22, 'TV-LED-32', 'Beko', 'LED', '32"', 189, 'Black', '1 year', 'HD', 'Smart TV, HDR'),
(23, 'TV-OLED-55', 'Sony', 'OLED', '55"', 1199, 'Black', '3 years', '4K', 'Google TV, Acoustic Surface'),
(24, 'TV-LED-55', 'Hisense', 'LED', '55"', 429, 'Black', '2 years', '4K', 'Vidaa, Game Mode Pro'),
(25, 'TV-MiniLED-75', 'TCL', 'Mini-LED', '75"', 1699, 'Silver', '3 years', '4K', 'Google TV, 144Hz VRR'),
(26, 'TV-LED-43', 'Philips', 'LED', '43"', 349, 'Black', '1 year', '4K', 'Android TV, Ambilight 3-sided'),
(27, 'TV-QLED-65', 'Samsung', 'QLED', '65"', 1099, 'Black', '2 years', '4K', 'Tizen, Quantum HDR'),
(28, 'TV-LED-50', 'Haier', 'LED', '50"', 379, 'Silver', '2 years', '4K', 'Android TV, MEMC'),
(29, 'TV-OLED-77', 'Sony', 'OLED', '77"', 2699, 'Black', '3 years', '4K', 'Google TV, XR OLED Contrast'),
(30, 'TV-LED-40', 'TCL', 'LED', '40"', 269, 'Black', '1 year', 'Full HD', 'Roku TV, HDR10'),
(31, 'TV-QLED-55', 'Panasonic', 'QLED', '55"', 749, 'Silver', '2 years', '4K', 'My Home Screen, HDR10+'),
(32, 'TV-LED-65', 'Hisense', 'LED', '65"', 579, 'Black', '2 years', '4K', 'Vidaa, Dolby Vision IQ'),
(33, 'TV-OLED-65', 'LG', 'OLED', '65"', 1399, 'Silver', '3 years', '4K', 'webOS, OLED evo'),
(34, 'TV-LED-32', 'Sharp', 'LED', '32"', 209, 'Black', '1 year', 'HD', 'Android TV, Aquos Net'),
(35, 'TV-MiniLED-65', 'Samsung', 'Mini-LED', '65"', 1399, 'Black', '2 years', '4K', 'Neo QLED, Quantum Matrix'),
(36, 'TV-LED-50', 'Beko', 'LED', '50"', 369, 'Silver', '2 years', '4K', 'Android TV, HDR10+'),
(37, 'TV-QLED-75', 'LG', 'QLED', '75"', 1699, 'Black', '3 years', '4K', 'webOS, Quantum Dot'),
(38, 'TV-LED-43', 'Haier', 'LED', '43"', 319, 'Black', '1 year', '4K', 'Android TV, PatchWall'),
(39, 'TV-OLED-55', 'Panasonic', 'OLED', '55"', 1099, 'Silver', '2 years', '4K', 'My Home Screen, Master OLED'),
(40, 'TV-LED-55', 'TCL', 'LED', '55"', 449, 'Black', '2 years', '4K', 'Google TV, AiPQ Engine'),
(41, 'TV-QLED-65', 'Hisense', 'QLED', '65"', 849, 'Silver', '2 years', '4K', 'Vidaa, ULED 4K'),
(42, 'TV-LED-40', 'Samsung', 'LED', '40"', 319, 'Black', '1 year', 'Full HD', 'Tizen, PurColor'),
(43, 'TV-OLED-83', 'LG', 'OLED', '83"', 3499, 'Black', '3 years', '4K', 'webOS, OLED EX Panel'),
(44, 'TV-LED-50', 'Philips', 'LED', '50"', 429, 'Silver', '2 years', '4K', 'Android TV, P5 Perfect'),
(45, 'TV-MiniLED-85', 'TCL', 'Mini-LED', '85"', 2299, 'Black', '3 years', '4K', 'Google TV, OD Mini LED'),
(46, 'TV-LED-32', 'LG', 'LED', '32"', 219, 'Black', '1 year', 'HD', 'webOS, ThinQ AI'),
(47, 'TV-QLED-55', 'Sony', 'QLED', '55"', 899, 'Silver', '2 years', '4K', 'Google TV, XR 4K Upscaling'),
(48, 'TV-LED-65', 'Samsung', 'LED', '65"', 699, 'Black', '2 years', '4K', 'Crystal Processor 4K, Q-Symphony'),
(49, 'TV-OLED-65', 'Hisense', 'OLED', '65"', 1199, 'Black', '2 years', '4K', 'Vidaa, Dolby Vision IQ'),
(50, 'TV-LED-43', 'Beko', 'LED', '43"', 299, 'Silver', '1 year', '4K', 'Android TV, HDR10'),
(51, 'TV-QLED-75', 'TCL', 'QLED', '75"', 1599, 'Black', '3 years', '4K', 'Google TV, Quantum Dot'),
(52, 'TV-LED-50', 'Sharp', 'LED', '50"', 389, 'Black', '2 years', '4K', 'Android TV, Aquos 4K'),
(53, 'TV-OLED-55', 'Samsung', 'OLED', '55"', 1299, 'Silver', '2 years', '4K', 'Tizen, Neural Quantum Processor'),
(54, 'TV-LED-40', 'Haier', 'LED', '40"', 259, 'Black', '1 year', 'Full HD', 'Android TV, MEMC Pro'),
(55, 'TV-MiniLED-75', 'Sony', 'Mini-LED', '75"', 2199, 'Black', '3 years', '4K', 'Google TV, XR Backlight Master'),
(56, 'TV-LED-55', 'Philips', 'LED', '55"', 529, 'Silver', '2 years', '4K', 'Android TV, Ambilight 4-sided'),
(57, 'TV-QLED-65', 'LG', 'QLED', '65"', 999, 'Black', '2 years', '4K', 'webOS, α7 AI Processor'),
(58, 'TV-LED-32', 'Hisense', 'LED', '32"', 179, 'Black', '1 year', 'HD', 'Vidaa, DTS Virtual:X'),
(59, 'TV-OLED-77', 'Panasonic', 'OLED', '77"', 2399, 'Black', '3 years', '4K', 'My Home Screen, Master OLED Pro'),
(60, 'TV-LED-43', 'Samsung', 'LED', '43"', 369, 'Black', '1 year', '4K', 'Tizen, Crystal Display'),
(61, 'TV-QLED-55', 'Haier', 'QLED', '55"', 549, 'Silver', '2 years', '4K', 'Android TV, Quantum Dot'),
(62, 'TV-LED-65', 'TCL', 'LED', '65"', 549, 'Black', '2 years', '4K', 'Google TV, AiPQ 3.0'),
(63, 'TV-OLED-65', 'Sony', 'OLED', '65"', 1599, 'Silver', '3 years', '4K', 'Google TV, XR Contrast Booster'),
(64, 'TV-LED-50', 'LG', 'LED', '50"', 419, 'Black', '2 years', '4K', 'webOS, Real 4K'),
(65, 'TV-MiniLED-65', 'Hisense', 'Mini-LED', '65"', 1099, 'Black', '2 years', '4K', 'Vidaa, ULED XD'),
(66, 'TV-LED-40', 'Beko', 'LED', '40"', 249, 'Silver', '1 year', 'Full HD', 'Android TV, Dolby Audio'),
(67, 'TV-QLED-85', 'Samsung', 'QLED', '85"', 2999, 'Black', '3 years', '4K', 'Neo QLED, Anti-Glare'),
(68, 'TV-LED-55', 'Sharp', 'LED', '55"', 469, 'Black', '2 years', '4K', 'Android TV, Aquos Pro'),
(69, 'TV-OLED-55', 'LG', 'OLED', '55"', 1149, 'Silver', '2 years', '4K', 'webOS, Self-Lit Pixels'),
(70, 'TV-LED-43', 'Panasonic', 'LED', '43"', 339, 'Black', '1 year', '4K', 'My Home Screen, Hexa Chroma'),
(71, 'TV-QLED-65', 'TCL', 'QLED', '65"', 899, 'Silver', '2 years', '4K', 'Google TV, 120Hz DLG'),
(72, 'TV-LED-50', 'Samsung', 'LED', '50"', 449, 'Black', '2 years', '4K', 'Crystal Processor, Motion Xcelerator'),
(73, 'TV-OLED-77', 'Hisense', 'OLED', '77"', 1899, 'Black', '3 years', '4K', 'Vidaa, Dolby Vision IQ'),
(74, 'TV-LED-32', 'Philips', 'LED', '32"', 229, 'Black', '1 year', 'HD', 'Android TV, Pixel Plus'),
(75, 'TV-MiniLED-75', 'LG', 'Mini-LED', '75"', 1999, 'Silver', '3 years', '4K', 'webOS, QNED MiniLED'),
(76, 'TV-LED-65', 'Haier', 'LED', '65"', 599, 'Black', '2 years', '4K', 'Android TV, MEMC 120Hz'),
(77, 'TV-QLED-55', 'Beko', 'QLED', '55"', 579, 'Silver', '2 years', '4K', 'Android TV, Quantum Dot'),
(78, 'TV-LED-40', 'TCL', 'LED', '40"', 289, 'Black', '1 year', 'Full HD', 'Roku TV, Micro Dimming'),
(79, 'TV-OLED-65', 'Samsung', 'OLED', '65"', 1499, 'Black', '2 years', '4K', 'Tizen, LaserSlim Design'),
(80, 'TV-LED-55', 'Hisense', 'LED', '55"', 479, 'Silver', '2 years', '4K', 'Vidaa, Game Mode Plus'),
(81, 'TV-QLED-75', 'Sony', 'QLED', '75"', 1999, 'Black', '3 years', '4K', 'Google TV, XR Triluminos Pro'),
(82, 'TV-LED-43', 'LG', 'LED', '43"', 359, 'Black', '1 year', '4K', 'webOS, AI Brightness'),
(83, 'TV-OLED-55', 'Panasonic', 'OLED', '55"', 1149, 'Silver', '2 years', '4K', 'My Home Screen, Filmmaker Mode'),
(84, 'TV-LED-50', 'Beko', 'LED', '50"', 399, 'Black', '2 years', '4K', 'Android TV, Vision Pro'),
(85, 'TV-MiniLED-65', 'Samsung', 'Mini-LED', '65"', 1499, 'Silver', '2 years', '4K', 'Neo QLED, Quantum HDR 32x'),
(86, 'TV-LED-32', 'Haier', 'LED', '32"', 189, 'Black', '1 year', 'HD', 'Android TV, Bezel Less'),
(87, 'TV-QLED-65', 'Philips', 'QLED', '65"', 949, 'Black', '2 years', '4K', 'Android TV, P5 IQ Processor'),
(88, 'TV-LED-65', 'Sharp', 'LED', '65"', 619, 'Silver', '2 years', '4K', 'Android TV, Aquos 4K Pro'),
(89, 'TV-OLED-83', 'Sony', 'OLED', '83"', 3799, 'Black', '3 years', '4K', 'Google TV, XR OLED Contrast Pro'),
(90, 'TV-LED-40', 'LG', 'LED', '40"', 299, 'Black', '1 year', 'Full HD', 'webOS, HDR10 Pro'),
(91, 'TV-QLED-55', 'TCL', 'QLED', '55"', 649, 'Silver', '2 years', '4K', 'Google TV, Mini LED Pro'),
(92, 'TV-LED-55', 'Panasonic', 'LED', '55"', 499, 'Black', '2 years', '4K', 'My Home Screen, HDR10+ Adaptive'),
(93, 'TV-OLED-65', 'Hisense', 'OLED', '65"', 1249, 'Black', '2 years', '4K', 'Vidaa, Game Mode Pro 144Hz'),
(94, 'TV-LED-43', 'Samsung', 'LED', '43"', 379, 'Silver', '1 year', '4K', 'Tizen, PurColor Pro'),
(95, 'TV-MiniLED-85', 'LG', 'Mini-LED', '85"', 2699, 'Black', '3 years', '4K', 'webOS, QNED evo'),
(96, 'TV-LED-50', 'Haier', 'LED', '50"', 409, 'Black', '2 years', '4K', 'Android TV, Dolby Atmos'),
(97, 'TV-QLED-75', 'Beko', 'QLED', '75"', 1499, 'Silver', '2 years', '4K', 'Android TV, Quantum Dot Pro'),
(98, 'TV-LED-32', 'TCL', 'LED', '32"', 199, 'Black', '1 year', 'HD', 'Roku TV, Mobile Mirroring'),
(99, 'TV-OLED-55', 'Philips', 'OLED', '55"', 1199, 'Black', '2 years', '4K', 'Android TV, Ambilight, P5 AI'),
(100, 'TV-LED-65', 'Samsung', 'LED', '65"', 729, 'Silver', '2 years', '4K', 'Crystal Processor, Object Tracking Sound Lite');

INSERT INTO dishwashers (id, name, brand, type, size, price, color, warranty, energy_rating, features) VALUES 
(1, 'DW-Built-12', 'Bosch', 'Built-in', '60cm 12 place', 449, 'Silver', '2 years', 'A++', 'EcoSilence, VarioBasket'),
(2, 'DW-Freest-14', 'Samsung', 'Freestanding', '60cm 14 place', 549, 'Black', '2 years', 'A+++', 'WaterWall, Zone Booster'),
(3, 'DW-Compact-6', 'LG', 'Compact', 'Tabletop 6 place', 299, 'White', '1 year', 'A+', 'QuadWash, Steam'),
(4, 'DW-Built-15', 'Siemens', 'Built-in', '60cm 15 place', 699, 'Silver', '3 years', 'A+++', 'iQ500, homeConnect'),
(5, 'DW-Freest-12', 'Whirlpool', 'Freestanding', '60cm 12 place', 399, 'White', '2 years', 'A++', '6th Sense, PowerClean Pro'),
(6, 'DW-Built-14', 'Bosch', 'Built-in', '60cm 14 place', 579, 'Black', '2 years', 'A+++', 'PerfectDry, RackMatic'),
(7, 'DW-Freest-13', 'LG', 'Freestanding', '60cm 13 place', 479, 'Silver', '2 years', 'A+++', 'QuadWash Pro, TrueSteam'),
(8, 'DW-Compact-8', 'Haier', 'Compact', 'Tabletop 8 place', 329, 'White', '1 year', 'A++', 'Dual Spray, Auto Sense'),
(9, 'DW-Built-12', 'Beko', 'Built-in', '45cm 12 place', 379, 'Silver', '2 years', 'A++', 'AquaIntense, ProSmart Inverter'),
(10, 'DW-Freest-14', 'Samsung', 'Freestanding', '60cm 14 place', 599, 'Stainless Steel', '2 years', 'A+++', 'AutoOpen Dry, WaterWall'),
(11, 'DW-Built-15', 'Miele', 'Built-in', '60cm 15 place', 999, 'Silver', '5 years', 'A+++', 'AutoDos, 3D MultiFlex'),
(12, 'DW-Freest-12', 'Siemens', 'Freestanding', '60cm 12 place', 499, 'White', '2 years', 'A+++', 'iQ300, varioSpeed Plus'),
(13, 'DW-Compact-6', 'Whirlpool', 'Compact', 'Tabletop 6 place', 279, 'Black', '1 year', 'A+', '6th Sense Live, Steam'),
(14, 'DW-Built-14', 'LG', 'Built-in', '60cm 14 place', 629, 'Silver', '2 years', 'A+++', 'QuadWash, TrueSteam+'),
(15, 'DW-Freest-13', 'Bosch', 'Freestanding', '60cm 13 place', 529, 'Black', '2 years', 'A+++', 'EcoSilence Drive, Home Connect'),
(16, 'DW-Built-12', 'Haier', 'Built-in', '45cm 12 place', 419, 'White', '2 years', 'A++', 'Dual Spray, ABT'),
(17, 'DW-Freest-14', 'Beko', 'Freestanding', '60cm 14 place', 449, 'Silver', '2 years', 'A+++', 'AquaIntense Pro, Steam Cure'),
(18, 'DW-Compact-8', 'Samsung', 'Compact', 'Tabletop 8 place', 369, 'White', '1 year', 'A++', 'StormWash, Auto Release'),
(19, 'DW-Built-15', 'Siemens', 'Built-in', '60cm 15 place', 749, 'Black', '3 years', 'A+++', 'iQ700, sensoFresh'),
(20, 'DW-Freest-12', 'Miele', 'Freestanding', '60cm 12 place', 849, 'Silver', '5 years', 'A+++', 'AutoOpen, Knock2Open'),
(21, 'DW-Built-14', 'Whirlpool', 'Built-in', '60cm 14 place', 549, 'Silver', '2 years', 'A+++', 'PowerClean Pro, Steam Refresh'),
(22, 'DW-Freest-13', 'LG', 'Freestanding', '60cm 13 place', 499, 'White', '2 years', 'A+++', 'QuadWash, Smart Diagnosis'),
(23, 'DW-Compact-6', 'Bosch', 'Compact', 'Tabletop 6 place', 319, 'Black', '1 year', 'A++', 'VarioDrum, Silence Plus'),
(24, 'DW-Built-12', 'Haier', 'Built-in', '45cm 12 place', 399, 'Silver', '2 years', 'A++', 'Dual Spray, Near Zero Water'),
(25, 'DW-Freest-14', 'Samsung', 'Freestanding', '60cm 14 place', 619, 'Black', '2 years', 'A+++', 'WaterWall, AutoOpen Dry'),
(26, 'DW-Built-15', 'Beko', 'Built-in', '60cm 15 place', 599, 'Silver', '2 years', 'A+++', 'AquaIntense, HarvestCare'),
(27, 'DW-Freest-12', 'Siemens', 'Freestanding', '60cm 12 place', 519, 'White', '2 years', 'A+++', 'iQ500, speedPerfect+'),
(28, 'DW-Compact-8', 'Whirlpool', 'Compact', 'Tabletop 8 place', 309, 'White', '1 year', 'A++', '6th Sense, Steam Wash'),
(29, 'DW-Built-14', 'Miele', 'Built-in', '60cm 14 place', 949, 'Silver', '5 years', 'A+++', 'AutoDos, ComfortClose'),
(30, 'DW-Freest-13', 'LG', 'Freestanding', '60cm 13 place', 529, 'Black', '2 years', 'A+++', 'QuadWash Pro, TrueSteam'),
(31, 'DW-Built-12', 'Bosch', 'Built-in', '45cm 12 place', 429, 'Silver', '2 years', 'A+++', 'EcoSilence, PerfectDry'),
(32, 'DW-Freest-14', 'Haier', 'Freestanding', '60cm 14 place', 469, 'White', '2 years', 'A+++', 'Dual Spray Pro, ABT+'),
(33, 'DW-Compact-6', 'Samsung', 'Compact', 'Tabletop 6 place', 289, 'Silver', '1 year', 'A+', 'StormWash Mini, Auto Release'),
(34, 'DW-Built-15', 'Whirlpool', 'Built-in', '60cm 15 place', 649, 'Black', '3 years', 'A+++', 'PowerClean Pro+, Steam Refresh+'),
(35, 'DW-Freest-12', 'Beko', 'Freestanding', '60cm 12 place', 389, 'White', '2 years', 'A++', 'AquaIntense, Fast+'),
(36, 'DW-Built-14', 'Siemens', 'Built-in', '60cm 14 place', 679, 'Silver', '2 years', 'A+++', 'iQ500, homeConnect'),
(37, 'DW-Freest-13', 'Miele', 'Freestanding', '60cm 13 place', 899, 'Black', '5 years', 'A+++', 'AutoOpen, Knock2Open'),
(38, 'DW-Compact-8', 'LG', 'Compact', 'Tabletop 8 place', 349, 'White', '1 year', 'A++', 'QuadWash, Steam+'),
(39, 'DW-Built-12', 'Haier', 'Built-in', '45cm 12 place', 409, 'Silver', '2 years', 'A+++', 'Dual Spray, PuriSteam'),
(40, 'DW-Freest-14', 'Bosch', 'Freestanding', '60cm 14 place', 559, 'Black', '2 years', 'A+++', 'EcoSilence Drive, RackMatic'),
(41, 'DW-Built-15', 'Samsung', 'Built-in', '60cm 15 place', 729, 'Silver', '3 years', 'A+++', 'WaterWall, AutoOpen, AI Wash'),
(42, 'DW-Freest-12', 'Whirlpool', 'Freestanding', '60cm 12 place', 419, 'White', '2 years', 'A+++', '6th Sense Live, PowerClean'),
(43, 'DW-Compact-6', 'Beko', 'Compact', 'Tabletop 6 place', 269, 'Black', '1 year', 'A+', 'AquaIntense, Mini Program'),
(44, 'DW-Built-14', 'LG', 'Built-in', '60cm 14 place', 649, 'Silver', '2 years', 'A+++', 'QuadWash, TrueSteam+, NFC'),
(45, 'DW-Freest-13', 'Siemens', 'Freestanding', '60cm 13 place', 549, 'White', '2 years', 'A+++', 'iQ300, varioSpeed'),
(46, 'DW-Built-12', 'Miele', 'Built-in', '45cm 12 place', 799, 'Silver', '5 years', 'A+++', 'AutoDos, 3D CutleryTray'),
(47, 'DW-Freest-14', 'Haier', 'Freestanding', '60cm 14 place', 489, 'Black', '2 years', 'A+++', 'Dual Spray Pro, Near Zero Water'),
(48, 'DW-Compact-8', 'Samsung', 'Compact', 'Tabletop 8 place', 359, 'Silver', '1 year', 'A++', 'StormWash, Auto Release Door'),
(49, 'DW-Built-15', 'Bosch', 'Built-in', '60cm 15 place', 719, 'Black', '3 years', 'A+++', 'Series 6, Home Connect'),
(50, 'DW-Freest-12', 'Beko', 'Freestanding', '60cm 12 place', 399, 'White', '2 years', 'A+++', 'AquaIntense Pro, Steam Cure+'),
(51, 'DW-Built-14', 'Whirlpool', 'Built-in', '60cm 14 place', 569, 'Silver', '2 years', 'A+++', 'PowerClean Pro, FreshCare+'),
(52, 'DW-Freest-13', 'LG', 'Freestanding', '60cm 13 place', 519, 'Black', '2 years', 'A+++', 'QuadWash Pro, Smart Pairing'),
(53, 'DW-Compact-6', 'Haier', 'Compact', 'Tabletop 6 place', 299, 'White', '1 year', 'A++', 'Dual Spray, ABT'),
(54, 'DW-Built-12', 'Siemens', 'Built-in', '45cm 12 place', 479, 'Silver', '2 years', 'A+++', 'iQ500, speedPerfect+'),
(55, 'DW-Freest-14', 'Miele', 'Freestanding', '60cm 14 place', 979, 'Black', '5 years', 'A+++', 'AutoDos, ComfortClose'),
(56, 'DW-Built-15', 'Samsung', 'Built-in', '60cm 15 place', 749, 'Silver', '3 years', 'A+++', 'WaterWall, AutoOpen, Zone Booster'),
(57, 'DW-Freest-12', 'Bosch', 'Freestanding', '60cm 12 place', 469, 'White', '2 years', 'A+++', 'EcoSilence, PerfectDry Plus'),
(58, 'DW-Compact-8', 'Whirlpool', 'Compact', 'Tabletop 8 place', 319, 'Silver', '1 year', 'A++', '6th Sense, Steam Hygiene'),
(59, 'DW-Built-14', 'Beko', 'Built-in', '60cm 14 place', 529, 'Black', '2 years', 'A+++', 'AquaIntense, HarvestFresh'),
(60, 'DW-Freest-13', 'Haier', 'Freestanding', '60cm 13 place', 479, 'White', '2 years', 'A+++', 'Dual Spray, PuriSteam+'),
(61, 'DW-Built-12', 'LG', 'Built-in', '45cm 12 place', 449, 'Silver', '2 years', 'A+++', 'QuadWash, TrueSteam'),
(62, 'DW-Freest-14', 'Siemens', 'Freestanding', '60cm 14 place', 589, 'Black', '2 years', 'A+++', 'iQ500, homeConnect'),
(63, 'DW-Compact-6', 'Miele', 'Compact', 'Tabletop 6 place', 549, 'White', '5 years', 'A+++', 'AutoDos, CutleryTray'),
(64, 'DW-Built-15', 'Whirlpool', 'Built-in', '60cm 15 place', 669, 'Silver', '3 years', 'A+++', 'PowerClean Pro+, Steam Refresh'),
(65, 'DW-Freest-12', 'Samsung', 'Freestanding', '60cm 12 place', 499, 'Black', '2 years', 'A+++', 'WaterWall, Auto Release'),
(66, 'DW-Built-14', 'Haier', 'Built-in', '60cm 14 place', 549, 'Silver', '2 years', 'A+++', 'Dual Spray Pro, ABT+'),
(67, 'DW-Freest-13', 'Bosch', 'Freestanding', '60cm 13 place', 539, 'White', '2 years', 'A+++', 'EcoSilence Drive, RackMatic'),
(68, 'DW-Compact-8', 'Beko', 'Compact', 'Tabletop 8 place', 309, 'Black', '1 year', 'A++', 'AquaIntense, Fast+'),
(69, 'DW-Built-12', 'Siemens', 'Built-in', '45cm 12 place', 499, 'Silver', '2 years', 'A+++', 'iQ300, varioSpeed Plus'),
(70, 'DW-Freest-14', 'LG', 'Freestanding', '60cm 14 place', 579, 'Black', '2 years', 'A+++', 'QuadWash Pro, TrueSteam+'),
(71, 'DW-Built-15', 'Miele', 'Built-in', '60cm 15 place', 1049, 'Silver', '5 years', 'A+++', 'AutoDos, 3D MultiFlex Tray'),
(72, 'DW-Freest-12', 'Whirlpool', 'Freestanding', '60cm 12 place', 429, 'White', '2 years', 'A+++', '6th Sense Live, PowerClean Pro'),
(73, 'DW-Built-14', 'Samsung', 'Built-in', '60cm 14 place', 649, 'Black', '2 years', 'A+++', 'WaterWall, AutoOpen, AI Control'),
(74, 'DW-Compact-6', 'Haier', 'Compact', 'Tabletop 6 place', 289, 'Silver', '1 year', 'A+', 'Dual Spray, Near Zero Water'),
(75, 'DW-Freest-13', 'Beko', 'Freestanding', '60cm 13 place', 439, 'White', '2 years', 'A+++', 'AquaIntense Pro, Steam Cure'),
(76, 'DW-Built-12', 'Bosch', 'Built-in', '45cm 12 place', 459, 'Silver', '2 years', 'A+++', 'PerfectDry, Silence Plus'),
(77, 'DW-Freest-14', 'Siemens', 'Freestanding', '60cm 14 place', 599, 'Black', '2 years', 'A+++', 'iQ500, speedPerfect+'),
(78, 'DW-Built-15', 'LG', 'Built-in', '60cm 15 place', 699, 'Silver', '3 years', 'A+++', 'QuadWash, TrueSteam, Smart Diagnosis'),
(79, 'DW-Compact-8', 'Miele', 'Compact', 'Tabletop 8 place', 599, 'White', '5 years', 'A+++', 'AutoDos, Knock2Open'),
(80, 'DW-Freest-12', 'Haier', 'Freestanding', '60cm 12 place', 449, 'Black', '2 years', 'A+++', 'Dual Spray, PuriSteam'),
(81, 'DW-Built-14', 'Whirlpool', 'Built-in', '60cm 14 place', 589, 'Silver', '2 years', 'A+++', 'PowerClean Pro+, FreshCare+'),
(82, 'DW-Freest-13', 'Samsung', 'Freestanding', '60cm 13 place', 559, 'White', '2 years', 'A+++', 'WaterWall, Zone Booster'),
(83, 'DW-Built-12', 'Beko', 'Built-in', '45cm 12 place', 409, 'Black', '2 years', 'A++', 'AquaIntense, ProSmart Inverter'),
(84, 'DW-Freest-14', 'Bosch', 'Freestanding', '60cm 14 place', 569, 'Silver', '2 years', 'A+++', 'EcoSilence Drive, Home Connect'),
(85, 'DW-Built-15', 'Haier', 'Built-in', '60cm 15 place', 679, 'Black', '3 years', 'A+++', 'Dual Spray Pro, ABT Pro'),
(86, 'DW-Compact-6', 'LG', 'Compact', 'Tabletop 6 place', 309, 'White', '1 year', 'A++', 'QuadWash, Steam+'),
(87, 'DW-Freest-12', 'Miele', 'Freestanding', '60cm 12 place', 879, 'Silver', '5 years', 'A+++', 'AutoOpen, ComfortClose'),
(88, 'DW-Built-14', 'Siemens', 'Built-in', '60cm 14 place', 689, 'Black', '2 years', 'A+++', 'iQ700, sensoFresh'),
(89, 'DW-Freest-13', 'Whirlpool', 'Freestanding', '60cm 13 place', 509, 'White', '2 years', 'A+++', '6th Sense, PowerClean'),
(90, 'DW-Built-12', 'Samsung', 'Built-in', '45cm 12 place', 469, 'Silver', '2 years', 'A+++', 'WaterWall, Auto Release Door'),
(91, 'DW-Freest-14', 'Haier', 'Freestanding', '60cm 14 place', 499, 'Black', '2 years', 'A+++', 'Dual Spray Pro, Near Zero Water+'),
(92, 'DW-Built-15', 'Bosch', 'Built-in', '60cm 15 place', 739, 'Silver', '3 years', 'A+++', 'Series 6, PerfectDry, Home Connect'),
(93, 'DW-Compact-8', 'Beko', 'Compact', 'Tabletop 8 place', 329, 'White', '1 year', 'A++', 'AquaIntense, Steam Cure'),
(94, 'DW-Freest-12', 'LG', 'Freestanding', '60cm 12 place', 489, 'Black', '2 years', 'A+++', 'QuadWash Pro, TrueSteam'),
(95, 'DW-Built-14', 'Miele', 'Built-in', '60cm 14 place', 969, 'Silver', '5 years', 'A+++', 'AutoDos, 3D MultiFlex'),
(96, 'DW-Freest-13', 'Siemens', 'Freestanding', '60cm 13 place', 569, 'White', '2 years', 'A+++', 'iQ500, varioSpeed Plus'),
(97, 'DW-Built-12', 'Whirlpool', 'Built-in', '45cm 12 place', 439, 'Silver', '2 years', 'A+++', 'PowerClean Pro, Steam Refresh'),
(98, 'DW-Freest-14', 'Beko', 'Freestanding', '60cm 14 place', 459, 'Black', '2 years', 'A+++', 'AquaIntense Pro, Fast+'),
(99, 'DW-Built-15', 'Haier', 'Built-in', '60cm 15 place', 699, 'Silver', '3 years', 'A+++', 'Dual Spray Pro, PuriSteam+'),
(100, 'DW-Freest-12', 'Samsung', 'Freestanding', '60cm 12 place', 519, 'White', '2 years', 'A+++', 'WaterWall, AutoOpen Dry');
